task releasemem;
	begin
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_0_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_1_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_2_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_3_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_4_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_5_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_6_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA0.IB0.IC0.ID0.IE0.DLTCH_7_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_0_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_1_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_2_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_3_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_4_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_5_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_6_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA1.IB0.IC0.ID0.IE0.DLTCH_7_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_0_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_1_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_2_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_3_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_4_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_5_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_6_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA2.IB0.IC0.ID0.IE0.DLTCH_7_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_0_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_1_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_2_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_3_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_4_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_5_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_6_.Q;
		release ITR_INFERENCE_sim.ICOR.ILAYER_BUFFER.I_X5.IA3.IB0.IC0.ID0.IE0.DLTCH_7_.Q;
	end
endtask
